INSERT INTO knowledge_points(knowledge_point_id, code, parent_id, domain, name_en, name_cn, description) VALUES
('KP-VOC', 'vocabulary', NULL, 'vocabulary', 'Vocabulary', '词汇', 'Vocabulary knowledge and retrieval.'),
('KP-VOC-RECALL', 'active_recall', 'KP-VOC', 'vocabulary', 'Active recall', '主动提取', 'Produce the target expression without recognition cues.'),
('KP-VOC-SPELL', 'spelling', 'KP-VOC', 'vocabulary', 'Spelling', '拼写', 'Orthographic accuracy.'),
('KP-VOC-PHRASE', 'fixed_phrase', 'KP-VOC', 'vocabulary', 'Fixed phrase', '固定搭配', 'Multi-word chunks and collocations.'),
('KP-VOC-FORM', 'word_form', 'KP-VOC', 'vocabulary', 'Word form', '词形变化', 'Inflection and derivation.'),
('KP-VOC-FAMILY', 'word_family', 'KP-VOC', 'vocabulary', 'Word family', '词族', 'Relations among derived forms.'),
('KP-VOC-SYN', 'near_synonym', 'KP-VOC', 'vocabulary', 'Near synonym', '近义词辨析', 'Selecting the source-calibrated expression among near synonyms.'),
('KP-GRA', 'grammar', NULL, 'grammar', 'Grammar', '语法', 'Grammar knowledge and application.'),
('KP-GRA-PRED', 'predicate_vs_non_predicate', 'KP-GRA', 'grammar', 'Predicate vs non-predicate', '谓语与非谓语判断', 'Decide whether a verb slot is finite or non-finite.'),
('KP-GRA-TENSE', 'tense', 'KP-GRA', 'grammar', 'Tense', '时态', 'Tense selection from time and discourse evidence.'),
('KP-GRA-VOICE', 'voice', 'KP-GRA', 'grammar', 'Voice', '语态', 'Active/passive voice.'),
('KP-GRA-SVA', 'subject_verb_agreement', 'KP-GRA', 'grammar', 'Subject-verb agreement', '主谓一致', 'Agreement between subject and finite verb.'),
('KP-GRA-NONFINITE', 'non_finite', 'KP-GRA', 'grammar', 'Non-finite verbs', '非谓语动词', 'Infinitives, gerunds and participles.'),
('KP-GRA-NOUNCLAUSE', 'noun_clause', 'KP-GRA', 'grammar', 'Noun clauses', '名词性从句', 'Subject, object, predicative and appositive clauses.'),
('KP-GRA-RELCLAUSE', 'relative_clause', 'KP-GRA', 'grammar', 'Relative clauses', '定语从句', 'Relative clause form and function.'),
('KP-GRA-ADVCLAUSE', 'adverbial_clause', 'KP-GRA', 'grammar', 'Adverbial clauses', '状语从句', 'Adverbial clause connectors and logic.'),
('KP-GRA-ARTICLE', 'article', 'KP-GRA', 'grammar', 'Articles', '冠词', 'Article choice and omission.'),
('KP-GRA-PRONOUN', 'pronoun', 'KP-GRA', 'grammar', 'Pronouns', '代词', 'Pronoun form, reference and dummy it.'),
('KP-GRA-PREP', 'preposition_collocation', 'KP-GRA', 'grammar', 'Prepositions and collocations', '介词与固定搭配', 'Preposition choice including fixed collocations.'),
('KP-GRA-INVERT', 'inversion', 'KP-GRA', 'grammar', 'Inversion', '倒装', 'Full and partial inversion.'),
('KP-READ', 'reading', NULL, 'reading', 'Reading', '阅读', 'Reading comprehension.'),
('KP-READ-MAIN', 'reading_main_idea', 'KP-READ', 'reading', 'Main idea', '主旨大意', 'Identify the central idea.'),
('KP-READ-DETAIL', 'reading_detail', 'KP-READ', 'reading', 'Detail', '细节理解', 'Locate and interpret explicit detail.'),
('KP-READ-INFER', 'reading_inference', 'KP-READ', 'reading', 'Inference', '推理判断', 'Infer unstated meaning from evidence.'),
('KP-READ-VOC', 'reading_vocab_context', 'KP-READ', 'reading', 'Vocabulary in context', '语境猜词', 'Infer word meaning from context.'),
('KP-TRANS', 'translation', NULL, 'translation', 'Translation', '翻译', 'Chinese-English and English-Chinese translation.'),
('KP-TRANS-STRUCT', 'translation_sentence_structure', 'KP-TRANS', 'translation', 'Sentence structure', '翻译句式结构', 'Build the main sentence skeleton and transformations.'),
('KP-WRITE', 'writing', NULL, 'writing', 'Writing', '写作', 'Written production.'),
('KP-WRITE-TASK', 'writing_task_fulfillment', 'KP-WRITE', 'writing', 'Task fulfillment', '任务完成度', 'Address all task requirements.'),
('KP-WRITE-ORG', 'writing_organization', 'KP-WRITE', 'writing', 'Organization', '篇章组织', 'Coherence and paragraph structure.'),
('KP-WRITE-LANG', 'writing_language', 'KP-WRITE', 'writing', 'Language', '语言表达', 'Grammar, vocabulary and style in writing.');

INSERT INTO error_types(error_type_id, code, parent_id, label_en, label_cn, description) VALUES
('ERR-KNOWLEDGE', 'knowledge_gap', NULL, 'Knowledge gap', '知识缺失', 'The underlying rule or meaning is not known.'),
('ERR-METHOD', 'method_gap', NULL, 'Method gap', '题型方法不熟', 'A stable solving procedure is missing or not applied.'),
('ERR-RECALL', 'active_recall_failure', NULL, 'Active recall failure', '主动提取失败', 'The target cannot be produced without cues.'),
('ERR-SPELL', 'spelling_error', NULL, 'Spelling error', '拼写错误', 'The intended target is recognizable but misspelled.'),
('ERR-PHRASE', 'fixed_phrase_missing', NULL, 'Fixed phrase missing', '固定搭配缺失', 'A required chunk or collocation is incomplete or replaced.'),
('ERR-SYN', 'near_synonym_substitution', NULL, 'Near-synonym substitution', '近义词替代', 'A near synonym replaces the calibrated target.'),
('ERR-FORM', 'word_form_error', NULL, 'Word form error', '词形错误', 'Incorrect inflection, derivation, or part of speech.'),
('ERR-FAMILY', 'word_family_confusion', NULL, 'Word-family confusion', '词族混淆', 'Confusion among related word-family members.'),
('ERR-TENSE-VOICE', 'tense_voice_confusion', NULL, 'Tense/voice confusion', '时态语态混淆', 'Tense or active/passive form is selected incorrectly.'),
('ERR-NONFINITE', 'non_finite_error', NULL, 'Non-finite verb error', '非谓语错误', 'Incorrect non-finite form or function.'),
('ERR-CLAUSE', 'clause_connector_error', NULL, 'Clause connector error', '从句连接词错误', 'Incorrect clause type or connector.'),
('ERR-INVERSION', 'inversion_error', NULL, 'Inversion error', '倒装错误', 'Required inversion is missing or malformed.'),
('ERR-STRUCTURE', 'sentence_structure_error', NULL, 'Sentence structure error', '句子结构错误', 'The sentence skeleton is incomplete or malformed.'),
('ERR-SOURCE', 'source_wording_mismatch', NULL, 'Source wording mismatch', '源书表达不一致', 'Response differs from the calibrated source expression.'),
('ERR-UNCERTAIN', 'needs_check', NULL, 'Needs check', '待核查', 'The legacy label is not safe to normalize more specifically.');

INSERT INTO error_type_aliases(alias_normalized, raw_alias, error_type_id, source_system) VALUES
('blank', 'blank', 'ERR-RECALL', 'legacy_review'),
('空白/不会提取', '空白/不会提取', 'ERR-RECALL', 'legacy_review'),
('未作答', '未作答', 'ERR-RECALL', 'legacy_review'),
('目标词提取失败', '目标词提取失败', 'ERR-RECALL', 'legacy_review'),
('spelling', 'spelling', 'ERR-SPELL', 'legacy_review'),
('拼写错误', '拼写错误', 'ERR-SPELL', 'legacy_review'),
('fixed phrase error', 'fixed phrase error', 'ERR-PHRASE', 'legacy_review'),
('fixed phrase missing', 'fixed phrase missing', 'ERR-PHRASE', 'legacy_review'),
('固定搭配缺失', '固定搭配缺失', 'ERR-PHRASE', 'legacy_review'),
('near-synonym substitution', 'near-synonym substitution', 'ERR-SYN', 'legacy_review'),
('近义词替代源书表达', '近义词替代源书表达', 'ERR-SYN', 'legacy_review'),
('近义替代目标词', '近义替代目标词', 'ERR-SYN', 'legacy_review'),
('word form', 'word form', 'ERR-FORM', 'legacy_review'),
('word-form confusion', 'word-form confusion', 'ERR-FORM', 'legacy_review'),
('词性混淆', '词性混淆', 'ERR-FORM', 'legacy_review'),
('word-family confusion', 'word-family confusion', 'ERR-FAMILY', 'legacy_review'),
('词族混淆', '词族混淆', 'ERR-FAMILY', 'legacy_review'),
('时态/被动混淆', '时态/被动混淆', 'ERR-TENSE-VOICE', 'legacy_review'),
('未来被动', '未来被动', 'ERR-TENSE-VOICE', 'legacy_review'),
('非谓语结果状语', '非谓语结果状语', 'ERR-NONFINITE', 'legacy_review'),
('疑问词+不定式', '疑问词+不定式', 'ERR-CLAUSE', 'legacy_review'),
('翻译主干/only when倒装', '翻译主干/Only when倒装', 'ERR-INVERSION', 'legacy_review'),
('句子结构不完整', '句子结构不完整', 'ERR-STRUCTURE', 'legacy_review'),
('source fixed wording', 'source fixed wording', 'ERR-SOURCE', 'legacy_review'),
('搭配/行位需确认', '搭配/行位需确认', 'ERR-UNCERTAIN', 'legacy_review'),
('源书词块主动提取（待原卷核对）', '源书词块主动提取（待原卷核对）', 'ERR-UNCERTAIN', 'legacy_review');

